networks:
  monorepo-network:
    driver: overlay
    attachable: true

configs:
  env:
    file: ../.env.production

services:
  frontend:
    image: monorepo-template-frontend:latest
    ports:
      - "4300:80"
    configs:
      - source: env
        target: /app/.env.production
    networks:
      - monorepo-network
    depends_on:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    command: nginx -g 'daemon off;'

  backend:
    image: monorepo-template-backend:latest
    ports:
      - "3001:3001"
    configs:
      - source: env
        target: /app/.env.production
    networks:
      - monorepo-network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
    command: pnpm -F server prod